"""Student table changes

Revision ID: 5a0985cc02e7
Revises: 
Create Date: 2021-11-12 02:17:05.074121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0985cc02e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('rk1_remaining_time', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('rk2_remaining_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'rk2_remaining_time')
    op.drop_column('students', 'rk1_remaining_time')
    # ### end Alembic commands ###
